#!/bin/bash

#export
export workspace="$HOME/Desktop/workspace"

#alias
alias cdhome='cd ~'
alias cdroot='cd /'
alias cdworkspace='cd $workspace'
alias ip="ifconfig | grep 'inet' | grep -v '127.0.0.1' | grep -v 'inet6' | awk '{print \$2}'"
alias lssize='du -sh ./* | sort -hr'

# history 命令时间格式
HIST_STAMPS="yyyy-mm-dd"

#Go
# Enable the go modules feature
export GO111MODULE=auto
# Set the GOPROXY environment variable
export GOPROXY=https://goproxy.io
